[project]
name = "daf"
version = "1.1.23"
description = "Django Audio Feed is a simple web application that allows to create custom RSS podcast feeds."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "flake8>=7.3.0",
    "markdown>=3.9",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
]
